# Generated by Django 2.1.2 on 2019-01-01 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=128)),
                ('re_process', models.TextField(verbose_name='重现过程')),
                ('test_point', models.TextField(verbose_name='测试要点')),
                ('data_prepare', models.TextField(verbose_name='数据设计')),
                ('bug_no', models.CharField(max_length=128)),
                ('remarks', models.TextField(verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='use_case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_case_no', models.CharField(max_length=128)),
                ('class_layer_one', models.CharField(max_length=128)),
                ('class_layer_two', models.CharField(max_length=128)),
                ('class_layer_three', models.CharField(max_length=128)),
                ('use_case_input', models.TextField(verbose_name='输入条件')),
                ('use_case_output', models.TextField(verbose_name='输出结果')),
                ('tester', models.CharField(max_length=128)),
                ('test_result', models.CharField(max_length=128)),
                ('exec_date', models.DateField(verbose_name='执行日期')),
                ('test_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usecase_management_app.test_bill')),
            ],
        ),
    ]
